version: '2'

services:
  jenkinsdata:
    build: jenkins-data
    container_name: jenkins-data

  jenkinsmaster:
    build: jenkins-master
    container_name: jenkins-master
    volumes_from:
      - jenkinsdata
    ports:
      - "50000:50000"

  nexus:
    image: sonatype/docker-nexus3
    container_name: jenkins-nexus
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      - "8123:8123"
    environment:
      - CONTEXT_PATH:/nexus

  jenkinsnginx:
    build: jenkins-nginx
    container_name: jenkins-nginx
    mem_limit: 256m
    ports:
      - "80:80"
      - "443:443"
    

volumes:
  nexus-data: {}
  #jenkins:
  #  image: salva-jenkins:0.0.1
  #  container_name: jenkins-master
    #build: .
  #  environment:
  #    JAVA_OPTS: $JAVAOPTS
  #    JENKINS_OPTS: $JENKINSOPTS
  #  ports:
  #    - "50000:50000"
  #    - "$JENKINSPORT:8080"
  #  volumes:
  #    - $LOCALDIR/jenkins_home:/var/jenkins_home
